# 站点信息
title: 斜风细雨不须归
email: 3302499@qq.com
description: > # no one


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.zhtua.com" # the base hostname & protocol for your site

markdown: redcarpet  
pygments: true
# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: tag

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# Social account
# twitter:  username
weibo: '3897518672'
github: pokestan
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: suyan-zh


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
disqus:
  shortname: suyan-zh

